### PR TITLE
Make the payload include the raw data of the delivery body.

### PR DESCRIPTION
**Pull request by fourdollars**

### CODE REVIEW

**Comment by fourdollars** [comment]
This commit makes https://github.com/probot/smee-client/pull/151 work.

**Comment by gsmet** [comment]
Hey there,

Any chance we could make progress on merging this pull request?

This is needed for https://github.com/probot/smee.io/issues/9 and, while it's not strictly necessary to be able to check the signature in development, I think it would be great if we could do it to avoid issues when pushing the app to production.

Thanks!

**Comment by CRogers** [comment]
Also needed for #78

**Review by wolfy1339 — APPROVED** [review]

**Comment by gsmet** [comment]
@wolfy1339 hey there! Have you deployed this change to smee.io as I don't see any `rawdata` in what I received from there.

Since I saw this got fixed, I wanted to implement signature checking for requests coming from smee.io but can't.

Am I missing something?

Thanks!

**Comment by gsmet** [comment]
(you probably don't remember me but we discussed a while ago when smee.io had some issues - I'm working on https://github.com/quarkiverse/quarkus-github-app/)

**Comment by wolfy1339** [comment]
Unfortunately, I have no control over the deployed version on smee.io

I'll see if I can't get in touch with the proper person to deploy a newer revision

**Comment by gsmet** [comment]
Thanks, that would be awesome. This has been a long standing issue on our side. Let me know how it goes :).

**Comment by gsmet** [comment]
@wolfy1339 any news on this front? Thanks!

**Pull request merged**
