### PR TITLE
working smee helm chart

### PR DESCRIPTION
**Pull request by MrAmbiG**
A dockerize.sh file to create and push the docker image to my own repo, you may change it to github official registry or add a workflow to please create and push this docker image to your registry repo. Separate deployment folder for the same. I have deployed and tested it on k8s version 19.
-----
[View rendered Deployment/Deployment.md](https://github.com/MrAmbiG/smee.io/blob/helm/Deployment/Deployment.md)

### CODE REVIEW

**Comment by MrAmbiG** [comment]
cc @zeke

**Comment by JasonEtco** [comment]
@MrAmbiG can you explain why this is needed? I don't think we should add this much code to the repo without being clear that its necessary.

**Comment by MrAmbiG** [comment]
In this era of cloud (public/private/hybrid), microservices, having a deployment only for a physical server may not be enough. Microsoft bought github and helm within a year, helm is the de facto deployment strategy for any apps on kubernetes. smee being a github product (and a microsoft's extended product) it would be nice to be able to have a ready made deployment package like this which lets users

1. horizontal auto scaling
2. vertical auto scaling
3. deploy on baremetal kubernetes (on prem)
4. deploy on azure AKS (another microsoft product), aws EKS, GCE, RKE cloud platforms
5. Uninterrupted upgrade
6. Uninterrupted rollback
7. Always on service (smee won't go down if the physical server of virtual machine on which it is installed is down)
smee goes down if the server on which it is installed goes down. Also dedicating an entire server for the smee may be a under or over commitment of a server. Containerizing this way and making it also available will help business with k8s to solve this problem. Currently if all our servers have a minimum of 256GB RAM, 2TB of SSD, then for us it will be a great under utilization of that server when we use it for smee. If we have it on k8s using helm, then it auto scales up or down depending on the usage.

**Comment by JasonEtco** [comment]
Gotcha. I'm familiar with Helm and Kubernetes, I meant more about why the code for this needs to live in _this_ repo. I don't think it does - people can use Smee with their own configuration, and having it here is out of scope for the project. Thank you for suggesting it though!

**Comment by MrAmbiG** [comment]
I guess I will create my own help repository, create and add all the helm charts for all github products, a side project. Currently we are using it this way, I am sure others might need it in future. Appreciate your time.

**Comment by rnkhouse** [comment]
This is a good to-have feature.

**Pull request closed without merging**
